on: [push]

name: build

jobs:
  check:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: rustup show
      - name: Run cargo check
        uses: actions-rs/cargo@v1.0.1
        with:
          command: check
